export default {
    // BRIDGE
    SEARCH_BRIDGE_LOADING: 'SEARCH_BRIDGE_LOADING',
    SEARCH_BRIDGE: 'SEARCH_BRIDGE',
    SEARCH_BRIDGE_CLEAR: 'SEARCH_BRIDGE_CLEAR',
    SEARCH_BRIDGE_COMPLETE: 'SEARCH_BRIDGE_COMPLETE',
    PAIRING_BRIDGE: 'PAIRING_BRIDGE',
    ADD_BRIDGE: 'ADD_BRIDGE',

    // THEME
    CHANGE_THEME: 'CHANGE_THEME',

    // GROUPS
    FETCH_ALL_GROUPS: 'FETCH_ALL_GROUPS',
    CHANGE_GROUP_STATE: 'CHANGE_GROUP_STATE',
    CHANGE_GROUP_ATTR: 'CHANGE_GROUP_ATTR',
    CREATE_GROUP: 'CREATE_GROUP',
    FETCH_GROUP: 'FETCH_GROUP',
    DELETE_GROUP: 'DELETE_GROUP',

    // LIGHTS
    FETCH_ALL_LIGHTS: 'FETCH_ALL_LIGHTS',
    FETCH_LIGHT: 'FETCH_LIGHT',
    // FETCH_NEW_LIGHT: 'FETCH_NEW_LIGHT',
    CHANGE_LIGHT_STATE: 'CHANGE_LIGHT_STATE',
    CHANGE_LIGHT_ATTR: 'CHANGE_LIGHT_ATTR',
    DELETE_LIGHT: 'DELETE_LIGHT',

    // SCENES
    FETCH_ALL_SCENES : 'FETCH_ALL_SCENES',
    CREATE_SCENE : 'CREATE_SCENE',
    DELETE_SCENE : 'DELETE_SCENE',

    // SCHEDULES
    FETCH_ALL_SCHEDULES : 'FETCH_ALL_SCHEDULES',
    CREATE_SCHEDULE : 'CREATE_SCHEDULE',

    // AUTHENTICATION
    CHANGE_AUTHENTICATION_STATE : 'CHANGE_AUTHENTICATION_STATE',
    CHANGE_HARDWARE_SUPPORT : 'CHANGE_HARDWARE_SUPPORT',

    // CLOUD
    CHANGE_CLOUD : 'CHANGE_CLOUD',
    CHANGE_CLOUD_TOKEN: 'CHANGE_CLOUD_TOKEN',

    // LOADING
    CHANGE_LOADING: 'CHANGE_LOADING'
}